module.exports={
	version:"13.03.alpha"
	server:{
		host:"",
		port:""
	},
	base_data:{
		revision:"d7e493c7d6c0114b00de5b9a5558dcf5f789787d"
		repo_url:"git://github.com/E5-Geo-Appliance/e5-configuration.git"
	},
	world_data:{
		lite:{
			revision:"",
			repo_url:"git://github.com/E5-Geo-Appliance/e5-world-lite.git"
		},
		full:{
			revision:"",
			repo_url:"git://github.com/E5-Geo-Appliance/e5-world.git"
		}
	}
};